name: scorpio
channels:
  - eesi
  - pytorch
  - conda-forge
  - bioconda
  - defaults
  - nvidia
dependencies:
  - python=3.10
  - numpy=1.26.4
  - h5py=3.10.0
  - joblib=1.3.2
  - pyyaml=6.0.1
  - biopython=1.83
  - pandas=2.2.1
  - scikit-learn=1.4.1.post1
  - matplotlib=3.8.3
  - tqdm=4.66.2
  - pytorch=2.2.1
  - torchvision=0.17.1
  - transformers=4.38.2
  - faiss-gpu=1.8.0
  - pytorch-lightning=1.9.0
  - pip
  - pip:
    - git+https://github.com/MsAlEhR/KmerTokenizer.git
